name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"


[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "db-newsnow"
database_id = "385c64ff-dd56-4e02-8600-860ae3af26fa"
